---
- ec2:
    region : us-west-1
    key_name: newDEvops
    instance_type: t2.micro
    image: ami-04b6c97b14c54de18  
    wait: yes
    group: 
      - "DEVSG"  
    vpc_subnet_id: subnet-017fa7fc1749fb7ff 
    assign_public_ip: yes
