---
- name : "read env variable"
  include_vars :
    file : "vars/{{ PROJECT }}_{{ ENV }}.yml"

- ec2:
    region : "{{ REGION }}"
    key_name: "{{ KEYNAME }}"
    instance_type: t2.micro
    image:  "{{ IMAGE }}"
    wait: yes
    group: 
      - "{{ SGNAME }}"  
    vpc_subnet_id: "{{ SUBID }}" 
    assign_public_ip: yes
